name: Lettings site CI

on: 
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout code
        uses: actions/setup-python@v2

      - name: Set up python
        uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: | 
          python -m venv venv
          source venv/bin/activate 
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          source venv/bin/activate 
          flake8 ./home ./lettings ./oc_lettings_site ./profiles

      - name: Run test
        run: | 
          export SECRET_KEY="${{ secrets.SECRET_KEY }}"
          export DJANGO_SETTINGS_MODULE="${{ secrets.DJANGO_SETTINGS_MODULE }}"
          source venv/bin/activate 
          coverage run -m pytest  # Exécute les tests avec coverage
          coverage report          # Affiche le rapport de couverture
          coverage xml             # Génère un fichier XML pour l'analyse future
          coverage report --fail-under=80  # Échoue si la couverture est inférieure à 80%

  build_and_push_docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Git commit hash
        id: git-commit
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
                ${{ secrets.DOCKER_USERNAME }}/oc_lettings:latest 
                ${{ secrets.DOCKER_USERNAME }}/oc_lettings:${{ env.COMMIT_HASH }}