name: Django CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout code
        uses: actions/setup-python@v2

      - name: Set up python
        uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: | 
          python -m venv venv
          source venv/bin/activate 
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          source venv/bin/activate 
          flake8 ./home ./lettings ./oc_lettings_site ./profiles

      - name: Run test
        run: | 
          source venv/bin/activate 
          pytest

    # - name: Upload coverage to Coveralls
    #   uses: coverallsapp/github-action@v2
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}

  build_and_push_docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/oc_lettings:latest    

  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: build
    # environment:
    #   name: 'production'
    #   url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    # permissions:
    #   id-token: write #This is required for requesting the JWT
        
    steps:
          #     - name: Download artifact from build job
          #       uses: actions/download-artifact@v3
          #       with:
          #         name: python-app
        
          #     - name: Unzip artifact for deployment
          #       run: unzip release.zip
              
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true
    
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'lettingssite'
          slot-name: 'production' 
          images: ${{ secrets.DOCKER_USERNAME }}/lettingssite:latest   